import { Staff } from "../types"

export const mockStaff: Staff[] = [
    {
        id: "s1",
        fullName: "Garcia, Maria",
        firstName: "Maria",
        lastName: "Garcia",
        email: "mgarcia@example.com",
        phoneNumber: "+1 305-555-0101",
        role: "admin",
        campusLocation: "Poinciana Campus",
        status: "active",
        avatarUrl: "",
    },
    {
        id: "s2",
        fullName: "Roberts, John",
        firstName: "John",
        lastName: "Roberts",
        email: "jroberts@example.com",
        phoneNumber: "+1 305-555-0102",
        role: "dispatcher",
        campusLocation: "Simpson Campus",
        status: "active",
    },
    {
        id: "s3",
        fullName: "Nguyen, Linh",
        firstName: "Linh",
        lastName: "Nguyen",
        email: "lnguyen@example.com",
        phoneNumber: "+1 305-555-0103",
        role: "allocator",
        campusLocation: "Neptune Campus",
        status: "inactive",
    },
    {
        id: "s4",
        fullName: "Smith, Alice",
        firstName: "Alice",
        lastName: "Smith",
        email: "asmith@example.com",
        phoneNumber: "+1 305-555-0104",
        role: "viewer",
        campusLocation: "Downtown Middle",
        status: "active",
    },
    {
        id: "s5",
        fullName: "Lopez, Carlos",
        firstName: "Carlos",
        lastName: "Lopez",
        email: "clopez@example.com",
        phoneNumber: "+1 305-555-0105",
        role: "operator",
        campusLocation: "Learning Center",
        status: "active",
    },
    {
        id: "s6",
        fullName: "Perez, Ana",
        firstName: "Ana",
        lastName: "Perez",
        email: "aperez@example.com",
        phoneNumber: "+1 305-555-0106",
        role: "superadmin",
        campusLocation: "Poinciana Campus",
        status: "active",
    },
]

export default mockStaff
